// src/components/landing/PricingSection.tsx
'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Check, Users, Zap, Crown, Gift } from 'lucide-react';

export function PricingSection() {
  const [ref, setRef] = useState<string | null>(null);

  useEffect(() => {
    // Lire depuis l'URL (?ref=CODE) ou depuis le cookie
    const params = new URLSearchParams(window.location.search);
    const refFromUrl = params.get('ref');
    const refFromCookie = document.cookie
      .split('; ')
      .find((r) => r.startsWith('referral_code='))
      ?.split('=')?.[1] ?? null;
    const code = refFromUrl || refFromCookie;
    if (code) setRef(code.toUpperCase());
  }, []);

  const signupUrl = (plan?: string) => {
    const base = plan ? `/signup?plan=${plan}` : '/signup';
    return ref ? `${base}${plan ? '&' : '?'}ref=${ref}` : base;
  };

  return (
    <section id="pricing" className="py-12 md:py-16">
      <div className="container mx-auto px-4 md:px-6 max-w-6xl">
        <div className="mb-6">
          <div className="text-xs uppercase tracking-wider text-[color:var(--text-muted)] mb-2">
            Tarifs
          </div>
          <h2 className="text-3xl font-semibold text-[color:var(--text-primary)] mb-3">
            Verebona automatise l'organisation de votre patrimoine.
          </h2>
          <p className="text-[color:var(--text-muted)] max-w-2xl">
            Ajoutez vos documents. Verebona les analyse, les classe, complète vos informations et fait remonter vos échéances importantes. Choisissez l'offre adaptée à vos besoins, seul ou à deux.
          </p>
        </div>

        {/* Bandeau essai — adapté selon parrainage */}
        {ref ? (
          <div className="flex items-center gap-3 mb-4 px-4 py-3 rounded-xl bg-blue-950/40 border border-blue-500/30">
            <Gift className="w-5 h-5 text-blue-400 flex-shrink-0" />
            <span className="text-sm text-blue-200">
              Code parrainage <span className="font-mono font-semibold">{ref}</span> appliqué —{' '}
              <strong className="text-white">3 mois offerts</strong> au lieu de 2 sur toutes les offres.
            </span>
          </div>
        ) : (
          <div className="flex items-center gap-2 mb-2 px-1">
            <span className="text-sm text-[color:var(--text-muted)]">
              <strong className="text-[color:var(--text-primary)]">2 mois offerts</strong> sur toutes les offres — aucun paiement aujourd'hui, carte bancaire requise.
            </span>
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 max-w-7xl">
          {/* Standard */}
          <Card className="border border-[rgba(31,41,55,0.95)] bg-[rgba(15,23,42,0.9)] rounded-2xl flex flex-col h-full">
            <CardContent className="p-5 flex flex-col flex-1">
              <div className="flex items-center gap-2 mb-1">
                <Zap className="w-5 h-5 text-slate-400" />
                <h3 className="text-lg font-medium">Standard</h3>
              </div>
              <p className="text-sm text-[color:var(--text-muted)] mb-3">
                Pour découvrir Verebona et centraliser vos premiers biens et documents.
              </p>
              <div className="text-3xl font-semibold mb-1 h-12 flex items-start">
                19 €<span className="text-base font-normal text-[color:var(--text-muted)]"> / an</span>
              </div>
              <Link href={signupUrl()} className="block mb-3">
                <Button variant="outline" className="w-full">
                  Choisir Standard
                </Button>
              </Link>
              <ul className="space-y-2 text-sm text-[color:var(--text-muted)]">
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-slate-400 mt-1" /><span>Jusqu'à 2 biens actifs</span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-slate-400 mt-1" /><span>Analyse automatique de 50 documents par an</span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-slate-400 mt-1" /><span>Recherche intelligente</span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-slate-400 mt-1" /><span>Agenda de mes biens</span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-slate-400 mt-1" /><span>Accès desktop et mobile</span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-slate-400 mt-1" /><span>Export ZIP de mes documents</span></li>
              </ul>
            </CardContent>
          </Card>

          {/* Premium */}
          <Card className="border border-[rgba(59,130,246,0.7)] bg-gradient-radial from-[rgba(59,130,246,0.25)] to-[rgba(15,23,42,0.98)] rounded-2xl shadow-[0_18px_40px_rgba(15,23,42,0.6)] relative flex flex-col h-full">
            <div className="absolute top-3 right-3 text-xs px-3 py-1 rounded-full bg-[rgba(15,23,42,0.95)] border border-[rgba(96,165,250,0.9)] text-[#bfdbfe]">
              Recommandé
            </div>
            <CardContent className="p-5 flex flex-col flex-1">
              <div className="flex items-center gap-2 mb-1">
                <Crown className="w-5 h-5 text-blue-400" />
                <h3 className="text-lg font-medium">Premium</h3>
              </div>
              <p className="text-sm text-[color:var(--text-muted)] mb-3">
                Pour ceux qui veulent des dossiers impeccables à présenter à un acheteur ou assureur.
              </p>
              <div className="text-3xl font-semibold mb-1 h-12 flex items-start">
                59 €<span className="text-base font-normal text-[color:var(--text-muted)]"> / an</span>
              </div>
              <Link href={signupUrl('premium')} className="block mb-3">
                <Button className="w-full rounded-full bg-gradient-to-br from-[#3b82f6] to-[#1d4ed8] hover:shadow-[0_18px_40px_rgba(37,99,235,0.45)] transition-all hover:translate-y-[-1px]">
                  Choisir Premium
                </Button>
              </Link>
              <ul className="space-y-2 text-sm text-[color:var(--text-muted)]">
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-[#3b82f6] mt-1" /><span><strong>Tout Standard +</strong></span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-[#3b82f6] mt-1" /><span>10 biens actifs</span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-[#3b82f6] mt-1" /><span>200 documents analysés par an</span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-[#3b82f6] mt-1" /><span>Synchronisation avec votre agenda personnel</span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-[#3b82f6] mt-1" /><span>Exports documentaires prêts à utiliser</span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-[#3b82f6] mt-1" /><span>Support prioritaire</span></li>
              </ul>
            </CardContent>
          </Card>

          {/* Duo */}
          <Card className="border border-[rgba(52,211,153,0.4)] bg-gradient-radial from-[rgba(52,211,153,0.12)] to-[rgba(15,23,42,0.98)] rounded-2xl relative flex flex-col h-full">
            <div className="absolute top-3 right-3 text-xs px-3 py-1 rounded-full bg-[rgba(15,23,42,0.95)] border border-[rgba(52,211,153,0.6)] text-[#6ee7b7] flex items-center gap-1">
              <Users className="w-3 h-3" />Nouveau
            </div>
            <CardContent className="p-5 flex flex-col flex-1">
              <div className="flex items-center gap-2 mb-1">
                <Users className="w-5 h-5 text-emerald-400" />
                <h3 className="text-lg font-medium">Premium Duo</h3>
              </div>
              <p className="text-sm text-[color:var(--text-muted)] mb-3">
                Partagez un espace Verebona à deux pour gérer ensemble vos biens, documents et échéances.
              </p>
              <div className="text-3xl font-semibold mb-1 h-12 flex items-start">
                79 €<span className="text-base font-normal text-[color:var(--text-muted)]"> / an</span>
              </div>
              <Link href={signupUrl('premium_duo')} className="block mb-3">
                <Button className="w-full rounded-full bg-gradient-to-br from-[#34d399] to-[#059669] border-emerald-500 hover:shadow-[0_18px_40px_rgba(52,211,153,0.35)] transition-all hover:translate-y-[-1px]">
                  Choisir Premium Duo
                </Button>
              </Link>
              <ul className="space-y-2 text-sm text-[color:var(--text-muted)]">
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-emerald-400 mt-1" /><span><strong>Tout Premium +</strong></span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-emerald-400 mt-1" /><span>2 membres sur un même compte</span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-emerald-400 mt-1" /><span>Espace commun : biens, documents, échéances</span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-emerald-400 mt-1" /><span>Gestion collaborative</span></li>
              </ul>
            </CardContent>
          </Card>

          {/* Premium Pro — bientôt */}
          <Card className="border border-[rgba(31,41,55,0.6)] bg-[rgba(15,23,42,0.6)] rounded-2xl flex flex-col h-full opacity-60">
            <CardContent className="p-5 flex flex-col flex-1">
              <div className="flex items-center gap-2 mb-1">
                <Crown className="w-5 h-5 text-purple-400" />
                <h3 className="text-lg font-medium">Premium Pro</h3>
              </div>
              <p className="text-sm text-[color:var(--text-muted)] mb-3">
                Pour les professionnels gérant plusieurs portefeuilles.
              </p>
              <div className="text-3xl font-semibold mb-1 h-12 flex items-start text-[color:var(--text-muted)]">
                Bientôt
              </div>
              <Button variant="outline" className="w-full mb-3" disabled>
                Bientôt disponible
              </Button>
              <ul className="space-y-2 text-sm text-[color:var(--text-muted)]">
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-purple-400/50 mt-1" /><span>Tout Premium +</span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-purple-400/50 mt-1" /><span>Gestion matériel professionnel</span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-purple-400/50 mt-1" /><span>Plusieurs utilisateurs avec rôles</span></li>
                <li className="flex items-start gap-2"><Check className="w-3 h-3 text-purple-400/50 mt-1" /><span>API et intégrations avancées</span></li>
              </ul>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  );
}

// src/sections/PricingSection.vue
<template>
<section id="pricing" style="background:#F5F8FD;color:#0F1B33;padding:88px 24px">
  <div style="max-width:1280px;margin:0 auto">
    <div class="vb-reveal" style="display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:14px;flex-wrap:wrap">
      <div>
        <div style="font-size:13.5px;letter-spacing:.15em;text-transform:uppercase;font-weight:800;color:#2563EB;margin-bottom:10px">Tarifs</div>
        <h2 style="font-size:44px;font-weight:600;letter-spacing:-.02em;color:#0F1B33;margin-bottom:10px;max-width:680px;line-height:1.12">Verebona automatise l'organisation de votre patrimoine.</h2>
        <p style="font-size:15.5px;color:#5B6577;max-width:620px">Ajoutez vos documents. Verebona les analyse, les classe, complète vos informations et fait remonter vos échéances importantes. Choisissez l'offre adaptée, seul ou à deux.</p>
      </div>
    </div>
    <div style="font-size:14px;color:#5B6577;margin-bottom:24px"><strong style="color:#0F1B33">2 mois offerts</strong> sur toutes les offres — aucun paiement aujourd'hui, carte bancaire requise.</div>
    <div class="vb-rgroup r-4" style="display:grid;grid-template-columns:repeat(4,1fr);gap:16px;align-items:stretch">
      <!-- Standard -->
      <div style="display:flex;flex-direction:column;padding:24px;border-radius:18px;background:#fff;border:1px solid #E6EBF3">
        <h3 style="font-size:18px;font-weight:600;color:#0F1B33;margin-bottom:6px">Standard</h3>
        <p style="font-size:13px;color:#5B6577;line-height:1.5;margin-bottom:16px;min-height:56px">Pour découvrir Verebona et centraliser vos premiers biens et documents.</p>
        <div style="font-family:'Bricolage Grotesque',sans-serif;font-size:32px;font-weight:600;color:#0F1B33;margin-bottom:16px">19 €<span style="font-size:15px;font-weight:400;color:#8A93A6"> / an</span></div>
        <a :href="signupUrl()" style="text-align:center;font-size:14px;font-weight:600;color:#0F1B33;padding:11px;border-radius:10px;border:1px solid #D3DBE8;margin-bottom:18px">Choisir Standard</a>
        <div style="display:flex;flex-direction:column;gap:10px;font-size:13px;color:#5B6577">
          <div style="display:flex;gap:9px"><span style="color:#2563EB;font-weight:700">✓</span>Jusqu'à 2 biens actifs</div>
          <div style="display:flex;gap:9px"><span style="color:#2563EB;font-weight:700">✓</span>Analyse de 50 documents / an</div>
          <div style="display:flex;gap:9px"><span style="color:#2563EB;font-weight:700">✓</span>Recherche intelligente</div>
          <div style="display:flex;gap:9px"><span style="color:#2563EB;font-weight:700">✓</span>Agenda de mes biens</div>
          <div style="display:flex;gap:9px"><span style="color:#2563EB;font-weight:700">✓</span>Accès desktop & mobile</div>
          <div style="display:flex;gap:9px"><span style="color:#2563EB;font-weight:700">✓</span>Export ZIP de mes documents</div>
        </div>
      </div>
      <!-- Premium (recommandé) -->
      <div style="display:flex;flex-direction:column;padding:24px;border-radius:18px;background:linear-gradient(180deg,#0E1B36,#0B1428);border:1px solid rgba(59,130,246,.5);position:relative;box-shadow:0 24px 50px rgba(15,27,51,.25)">
        <span style="position:absolute;top:16px;right:16px;font-size:11px;padding:4px 11px;border-radius:999px;background:rgba(59,130,246,.18);border:1px solid rgba(96,165,250,.7);color:#BFDBFE">Recommandé</span>
        <h3 style="font-size:18px;font-weight:600;color:#fff;margin-bottom:6px">Premium</h3>
        <p style="font-size:13px;color:#9DB0CE;line-height:1.5;margin-bottom:16px;min-height:56px">Pour des dossiers impeccables à présenter à un acheteur ou un assureur.</p>
        <div style="font-family:'Bricolage Grotesque',sans-serif;font-size:32px;font-weight:600;color:#fff;margin-bottom:16px">59 €<span style="font-size:15px;font-weight:400;color:#8DA0BE"> / an</span></div>
        <a :href="signupUrl()" style="text-align:center;font-size:14px;font-weight:600;color:#fff;padding:11px;border-radius:10px;background:linear-gradient(135deg,#3B82F6,#1D4ED8);margin-bottom:18px;box-shadow:0 12px 26px rgba(37,99,235,.4)">Choisir Premium</a>
        <div style="display:flex;flex-direction:column;gap:10px;font-size:13px;color:#9DB0CE">
          <div style="display:flex;gap:9px"><span style="color:#60A5FA;font-weight:700">✓</span><strong style="color:#EAF0FB">Tout Standard +</strong></div>
          <div style="display:flex;gap:9px"><span style="color:#60A5FA;font-weight:700">✓</span>10 biens actifs</div>
          <div style="display:flex;gap:9px"><span style="color:#60A5FA;font-weight:700">✓</span>100 documents analysés / an</div>
          <div style="display:flex;gap:9px"><span style="color:#60A5FA;font-weight:700">✓</span>Synchro avec votre agenda personnel</div>
          <div style="display:flex;gap:9px"><span style="color:#60A5FA;font-weight:700">✓</span>Exports documentaires prêts à l'emploi</div>
          <div style="display:flex;gap:9px"><span style="color:#60A5FA;font-weight:700">✓</span>Support prioritaire</div>
        </div>
      </div>
      <!-- Duo -->
      <div style="display:flex;flex-direction:column;padding:24px;border-radius:18px;background:#fff;border:1px solid rgba(52,211,153,.45);position:relative">
        <span style="position:absolute;top:16px;right:16px;font-size:11px;padding:4px 11px;border-radius:999px;background:rgba(52,211,153,.12);border:1px solid rgba(52,211,153,.5);color:#059669">Nouveau</span>
        <h3 style="font-size:18px;font-weight:600;color:#0F1B33;margin-bottom:6px">Premium Duo</h3>
        <p style="font-size:13px;color:#5B6577;line-height:1.5;margin-bottom:16px;min-height:56px">Partagez un espace Verebona à deux pour gérer ensemble biens, documents et échéances.</p>
        <div style="font-family:'Bricolage Grotesque',sans-serif;font-size:32px;font-weight:600;color:#0F1B33;margin-bottom:16px">79 €<span style="font-size:15px;font-weight:400;color:#8A93A6"> / an</span></div>
        <a :href="signupUrl()" style="text-align:center;font-size:14px;font-weight:600;color:#fff;padding:11px;border-radius:10px;background:linear-gradient(135deg,#34D399,#059669);margin-bottom:18px;box-shadow:0 12px 26px rgba(52,211,153,.32)">Choisir Premium Duo</a>
        <div style="display:flex;flex-direction:column;gap:10px;font-size:13px;color:#5B6577">
          <div style="display:flex;gap:9px"><span style="color:#059669;font-weight:700">✓</span><strong style="color:#0F1B33">Tout Premium +</strong></div>
          <div style="display:flex;gap:9px"><span style="color:#059669;font-weight:700">✓</span>2 membres sur un même compte</div>
          <div style="display:flex;gap:9px"><span style="color:#059669;font-weight:700">✓</span>Espace commun : biens, docs, échéances</div>
          <div style="display:flex;gap:9px"><span style="color:#059669;font-weight:700">✓</span>Gestion collaborative</div>
        </div>
      </div>
      <!-- Pro -->
      <div style="display:flex;flex-direction:column;padding:24px;border-radius:18px;background:#F3F5F9;border:1px solid #E6EBF3;opacity:.8">
        <span style="align-self:flex-start;font-size:11px;padding:4px 11px;border-radius:999px;background:#E7EBF2;border:1px solid #D3DBE8;color:#8A93A6;margin-bottom:8px">Bientôt</span>
        <h3 style="font-size:18px;font-weight:600;color:#5B6577;margin-bottom:6px">Premium Pro</h3>
        <p style="font-size:13px;color:#8A93A6;line-height:1.5;margin-bottom:16px;min-height:56px">Pour les professionnels gérant plusieurs portefeuilles.</p>
        <div style="font-family:'Bricolage Grotesque',sans-serif;font-size:28px;font-weight:600;color:#8A93A6;margin-bottom:16px">Bientôt</div>
        <div style="text-align:center;font-size:14px;font-weight:600;color:#A2ABBC;padding:11px;border-radius:10px;border:1px solid #D3DBE8;margin-bottom:18px">Bientôt disponible</div>
        <div style="display:flex;flex-direction:column;gap:10px;font-size:13px;color:#8A93A6">
          <div style="display:flex;gap:9px"><span style="color:#A78BFA;font-weight:700">✓</span>Tout Premium +</div>
          <div style="display:flex;gap:9px"><span style="color:#A78BFA;font-weight:700">✓</span>Gestion matériel professionnel</div>
          <div style="display:flex;gap:9px"><span style="color:#A78BFA;font-weight:700">✓</span>Plusieurs utilisateurs avec rôles</div>
          <div style="display:flex;gap:9px"><span style="color:#A78BFA;font-weight:700">✓</span>API & intégrations avancées</div>
        </div>
      </div>
    </div>
  </div>
</section>
</template>

<script setup lang="ts">
import { signupUrl } from '../config/urls'
</script>
